name: Gemini auto pun
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  autopun:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install google-generativeai

      - name: Generate & score pun
        env:
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python scripts/auto_pun.py
